sudo: required

services:
  - docker

install:
  - make build

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y ldap-utils

script:
  - make test1
  - make test2
  - make test3
  - make test4
  - make test5
  - make test6
  - make test7
  - make test8
  - make test9
