version: '3'
services:

  ldap-clone:
    image: mlan/openldap
    networks:
      - backend
    ports:
      - "389:389"
    volumes:
      - ./seed:/var/lib/openldap/seed

  ldap-init:
    image: mlan/openldap
    networks:
      - backend
    ports:
      - "389:389"
    environment:
      - LDAP_DOMAIN=example.com
      - LDAP_ROOTCN=admin
      - LDAP_ROOTPW={SSHA}KirjzsjgMvjqBWNNof7ujKhwAZBfXmw3

  ldap-persist:
    image: mlan/openldap
    networks:
      - backend
    environment:
      - LDAP_LOGLEVEL=parse
    volumes:
      - ldap-conf:/srv/conf
      - ldap-data:/srv/data

volumes:
  ldap-conf:
  ldap-data:

networks:
  backend:
